### ISSUE TITLE
AddOn missing from AMO?

### ISSUE THREAD

**Issue by asleepysamurai** [Infocatcher/Right_Links_WE#10]
Hi,
   Has the add-on recently been removed from AMO? I've been recommending this add-on as a replacement for my no longer maintained [Right Click Link New Tab](https://addons.mozilla.org/en-US/firefox/addon/right-click-link-new-tab/) extension. 

   Will the add-on be available on AMO again, in the near future? Should I stop recommending it? Is the add-on being actively developed? If it is not being actively developed, I would like to adopt the project and continue development. Please do let me know.

Regards,
Balaganesh Damodaran

**Comment by Infocatcher** [comment]
> Has the add-on recently been removed from AMO?

This is how the new AMO works: first was removed/hidden all beta versions without ability to make them public and then was removed entire extension as obsolete.
Should I keep support Firefox/AMO developers with such policies and no respect to extensions developers (and for users too)? May be no.
But should I keep support users? Of course, yes...
So, I will continue to support Right Links.

**Comment by asleepysamurai** [comment]
Have you tried promoting any of the beta versions to a release version? I think your addon got unfairly caught in the 'Classic Addons' purge. Your extension is really good, and for a lot of people AMO is the only place to download extensions from. I would urge you to consider uploading the last beta as a 0.0.1 version of a new extension, so users can start downloading it again.

**Comment by Kadazo** [comment]
I've been using Right Links for a long time with simply just one right click then open link in new tab. It's very useful when browsing forums and searching information on the search engine. I can't find any other trustworthy add-on to replace Right Links. Please do not abandon it.

**Comment by asleepysamurai** [comment]
I would really appreciate it if you could get the extension back on AMO, perhaps under a new name. If you're not willing to do it, I wouldn't mind doing it. However, I really prefer if you would put it back on AMO yourself, since you are the original developer, and it would be best if you had direct control over the AMO listing.

Please reconsider putting this extension on AMO again.

**Comment by Infocatcher** [comment]
I thing, it's better to keep the same ID, but add WE to name.
Today I've added [some improvements](https://github.com/Infocatcher/Right_Links_WE/commits/6e7afac15d7b43d221a4fdcc6ca404c49717349e)... may be I'll have time to release it in some days.

**Comment by asleepysamurai** [comment]
Thank you! Looking forward to seeing the extension back on AMO :)

**Comment by StanGets** [comment]
@Infocatcher ,

> So, I will continue to support Right Links.

> Released on AMO:
> Right Links WE 0.5b7

Great! Thanks! Right Links WE has always performed excellently, happy to have it on AMO!

**Comment by asleepysamurai** [comment]
Thank you!
