### ISSUE TITLE
Blob option for images

### ISSUE THREAD

**Issue by Gitoffthelawn** [Infocatcher/Right_Links_WE#13]
Right Links WE previously had a `blob` option that could be configured in the settings.  I noticed it is no longer there.

Was this removed intentionally?  If so, I'm curious to learn and understand why.

**Comment by Infocatcher** [comment]
Was hidden in 6ee4ae4d2b3c11a21452319cb767215c4bec859e commit: looks like there is no way to open data:… URL in new tab using WebExtensions API. :(

**Comment by Gitoffthelawn** [comment]
Thanks.  What happens if a user already had it enabled?  Will it just be ignored?

**Comment by Infocatcher** [comment]
Yes, will be ignored and will always work like for canvasImagesUseBlob = true.

**Comment by Gitoffthelawn** [comment]
Thank you!  Your hard work is appreciated! :+1:
