### ISSUE TITLE
0.5b9 broken on FF 70.0b9

### ISSUE THREAD

**Issue by MOFTAD** [Infocatcher/Right_Links_WE#20]

**Comment by Yaron10** [comment]
@Infocatcher,

I wouldn't like to update to FF 70 if EightLinks does not work with that version.
Could you please confirm that this is indeed the case?
If it is, can you fix it?

Thank you for this great extension.

**Comment by Infocatcher** [comment]
Hmm, very strange, as I see, works fine with Firefox 70...
May be something was somehow misconfigured.

**Comment by Yaron10** [comment]
Great. :+1: 
Thank you for testing it.
