### ISSUE TITLE
Simple resquest: Open in discarded tab

### ISSUE THREAD

**Issue by EstherMoellman** [Infocatcher/Right_Links_WE#22]
Hi @Infocatcher ,

Firstly, thank you for your add-on.

Please, a simple request: Add an option to open links always in new discarded tab.
Thank you.

**Comment by Infocatcher** [comment]
Test version: <a href="http://infocatcher.ucoz.net/temp/rl/right_links_we-0.5b10pre.xpi">right_links_we-0.5b10pre.xpi</a> (<a href="https://github.com/Infocatcher/Right_Links_WE/tree/800b5a39d0f80150ca1615b5f29bdea3dca324f0">source code</a>).
(about:debugging -> This Firefox -> Load Temporary Add-on…)

**Comment by EstherMoellman** [comment]
So I tried the "tested version"... very nice! It seems to work like a charm. Great job. Congrats.
I hope to see soon the updated version at AMO.
Thank you!
