### ISSUE TITLE
Left clicks stopped working in many random cases (on links, buttons) when Right Links WE is on

### ISSUE THREAD

**Issue by baack** [Infocatcher/Right_Links_WE#37]
Left clicks stop working in many cases (on links, buttons), like once in 10 clicks. And when this situation happens, no left clicks are working even when clicked multiple times, until something like left mouse button dragging is made. Disabling Right Links WE makes it work again.
Firefox 120. GNU+Linux.

The situation happens a lot during the last months or something. I tried different Linux versions, different Right Links WE settings, but with no improvements.

Using right links for a long time.
It is so cool, and no alternatives exist, so, please do something to fix it.

**Comment by Gitoffthelawn** [comment]
On which version of Firefox did you start experiencing this with Right Links WE?  (Did it start with 120, or before?)

**Comment by baack** [comment]
@Gitoffthelawn thanks for swift response. No, before 120, probably around 116.0.1.
At least on 116.0.1 it also happens. Before 116 - not sure, maybe not.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Please note that I'm not the developer of this excellent tool, just an avid user like yourself.

Would it be possible for you to test with the ESR version of Firefox, which is currently Firefox 115?

https://www.mozilla.org/firefox/enterprise/

(To get to the Linux downloads, click the "another language or platform" link on that page.)

**Comment by baack** [comment]
> Would it be possible for you to test with the ESR version of Firefox, which is currently Firefox 115?

Well, Firefox profiles are not acting reliable when the Firefox version is downgraded. Only forward. So, I can only create new profiles and use it, but it may not reproduce, as the real profile I use extensively (remember, bug is random) and the addons and prefs configuration will be way simpler. So, is it really necessary to use 115?I would prefer to make any tests in 120+.

**Comment by Gitoffthelawn** [comment]
Nope... not necessary.  I'm trying to think of what could be causing the issue for you, and the different variables involved.

So far, you're the only one reporting the issue, but of course, that doesn't mean you're the only one experiencing it.  It's concerning because you have tried multiple versions of Linux.  Did you actually mean versions or did you mean distros?

How many Firefox extensions do you have installed (and enabled)?  How many plugins?

Here's my recommendation, and I realize it's not ideal or fun: Create a new profile with Firefox v120+ with no other extensions or plugins (or with as few extensions and plugins as you can possibly be productive).  See if the issue reproduces in that scenario.  If you have many extensions or plugins, I realize that you may lose some of your favourites in that profile, but perhaps you can use that profile for certain activities in which you don't need all of them.

Does that sound reasonable to you?

**Comment by baack** [comment]
> So far, you're the only one reporting the issue, but of course, that doesn't mean you're the only one experiencing it. It's concerning because you have tried multiple versions of Linux. Did you actually mean versions or did you mean distros?

Distros: Ubuntu, Fedora.
Versions: 116.0.1 and 120.0.1.
Two different PCs. Something broke recently, less than a year, more than a month ago.

> How many Firefox extensions do you have installed (and enabled)? How many plugins?

Like a dozen. The only one that may affect or cause this regression is probably uBlock Origin. I also have some prefs that are not default, mainly from well-known arkenfox user.js hardening, also a factor.

About the way to test. Yes, I can try to reproduce this on new profile on 115, or new profile on 120+ without extensions (except uBlock Origin. But I have to find out the way to do it a bit more reliable. Because sometimes I do not have it in a day or two, but sometimes I have it several times an hour. I think phpBB forums or something are more likely to have this ignoring-left-click situation.

P.S. When I get into this situation, do you want me to investigate something in developer's instrument or something?

**Comment by Gitoffthelawn** [comment]
Is there any possibility that this could be related to a hardware issue?  For example, I have a keyboard on which one key occasionally does not register a click, even when I press it.  It started happening a couple years ago and only happens once in a while, seemingly at random intervals.

To that end, has this issue ever occurred outside of Firefox?

I am currently using Firefox ESR (which is at v115.x.y right now), and am not experiencing any problems with Right Links.  But, of course, my Firefox profile is not identical to the one you are using.  And I'm sure there are hardware differences, driver differences, etc.

In the Right Links extension's options UI, please enable **Debug mode**.

Then, when this does occur within Firefox, open the *Browser Console*, enable its *Multiprocess Mode* (radio button to select that mode located at the top of the *Browser Console* window), and then enable **Errors**, **Warnings**, **Logs**, **Info**, and **Debug** in the filter row, and disable **CSS**, **XHR**, and **Requests** in that same row.

The *Browser Console* may reveal relevant details as to what is happening.  You can report such details here.

@Infocatcher Are you around?  I'm hoping so, as you may have additional ideas.

**Comment by baack** [comment]
> Is there any possibility that this could be related to a hardware issue? For example, I have a keyboard on which one key occasionally does not register a click, even when I press it. It started happening a couple years ago and only happens once in a while, seemingly at random intervals.

100% not a hardware issue. Started happening on 2 PCs in the same period of time (half a year) with the same symptoms. The keyboard hotkey that toggles Right Links WE instantly fixes the problem.

> To that end, has this issue ever occurred outside of Firefox?
No, never.




> In the Right Links extension's options UI, please enable **Debug mode**.

Thank you, I will activate it.

**Comment by baack** [comment]
I have an idea that it can be connected to the mouse move tolerance (bug #36). I do not have this bug, but maybe due to some Firefox changes the tolerance is not calculated properly and clicks are considered as too long mouse moves to react as clicks? A bit farfetched, because my problem is with left mouse clicks, not sure if the code of the addon can nor should affect it in the first place.

**Comment by baack** [comment]
* I got in this situation again. Left Clicks on a fake checkbox (`span` tag that is connected with `input`) was not working, nothing was happening. I left-clicked many times.
* Than I opened debugging console with Ctrl+Shift+I and clicked again - it was fixed, click was working normally no matter how many times I clicked.

**Debug mode** in the Right Links WE was active, but console had no useful information. If I am not mistaken, no messages from addon at all (no `[Right Links WE]`) because I was not right-clicking on this page before the bug happened. If I also checked, that when I right click, I get `[Right Links WE]` messages in the log, so the Debug mode is working.

**Comment by Gitoffthelawn** [comment]
Thanks for reporting that it's not a hardware issue.  Too bad that it's not, because that's a simple fix!

It's unfortunate that nothing relevant was present in the Browser Console.  However, the fact that it happened on a fake checkbox may be relevant.  Did you have any other extensions installed (besides uBO) when this occurred?  Did you have a `userContent.css` file in your Firefox profile?

Is the experienced you had with that fake checkbox reproducible?

What are your Right Links settings?

This is what has been working successfully for me:
 - long left-click disabled (although I previously had it enabled without issue)
 - right-click enabled
    - open links in background
    - open in new tab
    - context menu timeout: 200ms
 - mouse tolerance: 6px
Everything else is currently disabled within Right Links.

If you like, try duplicating the above settings, and see if there is any improvement.

**Comment by baack** [comment]
> It's unfortunate that nothing relevant was present in the Browser Console. However, the fact that it happened on a fake checkbox may be relevant.

I just had it on the github issue in this list: https://github.com/notifications
Left clicking was not opening it (also completely ignoring clicks)

> Did you have any other extensions installed (besides uBO) when this occurred?

Plenty, but none that I installed new in a year (only updates).


> Did you have a `userContent.css` file in your Firefox profile?

Yes, rather big one (for Tree Style Tab)


> What are your Right Links settings?

I tried default and different changes, nothing helped. I can try setting yours, thank you.

P.S.
When I had this on github notification list, I tried to press Alt twice (show menu bar and hide) and left-clicking also was fixed. So, now I am not that sure that it is a Right Links WE problem, because previously I was certain as the shortcut for on/off of the addon was fixing the problem, but maybe any shortcut fixes it. In this case it is not obvious what is the origin of this bug.

**Comment by Gitoffthelawn** [comment]
Is there any chance that you are accidentally toggling off Right Links WE via a keyboard shortcut?

This happened to me once.  I had a seldom used keyboard shortcut set to toggle Right Links WE.  I accidentally pressed that keyboard shortcut, and I thought Right Links WE was broken.  It took me several minutes of debugging to discover what I had done.

For this reason, I recommend removing the keyboard shortcut that toggles Right Links WE on/off from the Right Links WE settings UI and *also* from the Firefox `about:addons` UI (`Manage Extension Shortcuts` page within that UI).

**Comment by baack** [comment]
> Is there any chance that you are accidentally toggling off Right Links WE via a keyboard shortcut?

Not possible, not in this case.

And once again, the problem is not that right clicks stop working, it's left clicks that get ignore under some strange conditions.

**Comment by baack** [comment]
I started using Firefox without Light Links WE (painful), and found out that the issues still happens (also quite rare). So, I am sure now that the issue is not related to Right Links WE and closing the ticket. @Gitoffthelawn, thanks for discussion anyway.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thanks for reporting back. I hope you find the cause of the issue you are experiencing.
