### ISSUE TITLE
v.0.5b5 totaly does not work

### ISSUE THREAD

**Issue by Marcosdw** [Infocatcher/Right_Links_WE#4]
Hello,

v.0.5b5 does not work at all in linux mint 18.2 FF57.

Greetings

**Comment by Infocatcher** [comment]
Already reported about something weird after b4 -> b5 update. Was fixed by clicking on toolbar button.
And how it work on new Firefox profile (with clean install)?

**Comment by Marcosdw** [comment]
Yes, works fine, I did not click on the toolbar button ;)
