### ISSUE TITLE
Not working on FF 132.0.2

### ISSUE THREAD

**Issue by sir-harlekin** [Infocatcher/Right_Links_WE#40]
The addon suddenly stops working. On right click I only get the default right click menu.

Is there anything I can do to debug?

**Comment by Infocatcher** [comment]
As I see, there is no breaking changes in Firefox 132.0.2…
So, first of all please check state of "Enabled" and "Right-click" options:
![Screenshot: Right Links options](https://github.com/user-attachments/assets/a0ce1881-a32a-4f41-81ae-89e4afe3a422)

Also you turn on "Debug mode" checkbox and sheck for Right Links activity in Browser Console (Crtl+Shift+J to open):
![Screenshot: Browser Console](https://github.com/user-attachments/assets/d23434ee-0975-49d1-8de4-adf536e0b809)

**Comment by sir-harlekin** [comment]
Sorry for the inconvinience it seems there was a problem on my side.
Seems to be working fine now.
Keep up the great work.

**Comment by Gitoffthelawn** [comment]
@sir-harlekin BTW, if you don't use the F2 key to enable/disable Right Links, I recommend you disable that shortcut key.  It's easy to accidentally press it and mistakenly think the extension is broken.
