### ISSUE TITLE
"Error: Illegal Url" with Google Maps

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/Right_Links_WE#8]
Long left-click on maps.google.com gives the following error.

```
Error: Illegal URL:
blob:https://www.google.com/...
```

**Comment by Gitoffthelawn** [comment]
@Infocatcher What's the story with this?

**Comment by Infocatcher** [comment]
Should be fixed in development version: https://github.com/Infocatcher/Right_Links_WE/commit/0a0d5bb1fa52dfea9c8cb78827eeed2348647e81
